#!/usr/bin/env python
"""Generate weekly model performance report."""

from __future__ import annotations

import json
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


def generate_weekly_report(output_dir: str | None = None) -> str:
    today = date.today()
    week_ago = today - timedelta(days=7)

    lines: list[str] = [
        f"# SMDA Weekly Performance Report",
        f"**Period:** {week_ago.isoformat()} to {today.isoformat()}",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Summary",
        "",
    ]

    try:
        from src.analyzer.cost_auditor import cost_auditor
        audit = cost_auditor.audit()
        lines.extend([
            f"- **Total LLM cost (30 days):** ${audit.total_cost:.4f}",
            f"- **Savings vs all-Sonnet:** {audit.savings_percent:.1f}%",
            f"- **GPT-4o-mini calls:** {audit.mini_calls:,}",
            f"- **Claude Sonnet calls:** {audit.sonnet_calls:,}",
            f"- **Cache hit rate:** {cost_auditor.get_cache_hit_rate()*100:.1f}%",
            f"- **Within budget:** {'✅ Yes' if audit.is_within_budget() else '⚠️ Over budget'}",
        ])
    except Exception as e:
        lines.append(f"- Cost audit unavailable: {e}")

    lines.extend(["", "## Model Performance", ""])

    try:
        from src.analyzer.calibration import calibration_loop
        result = calibration_loop.compute_calibration()
        lines.extend([
            f"- **Calibration samples:** {result.samples_count}",
            f"- **False positive rate:** {result.false_positive_rate*100:.2f}%",
            f"- **False negative rate:** {result.false_negative_rate*100:.2f}%",
            f"- **Mean error:** {result.mean_error:.4f}",
            f"- **Recommended HIGH threshold:** {result.recommended_threshold_high:.4f}",
            f"- **Calibration confidence:** {result.confidence}",
        ])
    except Exception as e:
        lines.append(f"- Calibration unavailable: {e}")

    lines.extend(["", "## Few-Shot Examples", ""])
    try:
        from src.analyzer.few_shot_refresher import few_shot_refresher
        counts = few_shot_refresher.get_all_language_counts()
        for lang, count in sorted(counts.items()):
            lines.append(f"- **{lang}:** {count} examples")
    except Exception as e:
        lines.append(f"- Example stats unavailable: {e}")

    lines.extend([
        "",
        "## Pattern Library",
        "",
        f"Pattern YAML files in `data/manipulation_patterns/` are updated weekly via `scripts/update_patterns.py`.",
        "",
        "---",
        "*Auto-generated by SMDA weekly reporter*",
    ])

    report = "\n".join(lines)

    if output_dir:
        out_path = Path(output_dir) / f"weekly-report-{today.isoformat()}.md"
        out_path.write_text(report, encoding="utf-8")
        print(f"Report saved to {out_path}")
    else:
        print(report)

    return report


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Generate weekly performance report")
    parser.add_argument("--output-dir", help="Directory to save the report")
    args = parser.parse_args()
    generate_weekly_report(args.output_dir)


if __name__ == "__main__":
    main()
